### ISSUE TITLE
CliInputOptions for CliInputOption.OPT_TARGET with default values don't get added to the CliInputCommand

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#105]
**Describe the bug**
In getCollectCommand and getAssessCommand I return a CliInputCommand with a cmdOpts that has a CliInputOption, using the CliInputOption.OPT_TARGET name, with a default value.
When getCollection or getRecommendation are called, there are no flags with the CliInputOption.OPT_TARGET name in the CliInputCommand provided as a parameter, so the default target is lost, and the underlying sdk code instead assumes a target of `""`

**To Reproduce**
Create CliInputOption for OPT_TARGET with a default value
`CliinputOption targetOption = new CliInputOption(null, CliInputOption.OPT_TARGET, "description", true, true, "TARGET", "Default Value")`
Return the option in getCollectCommand and/or getAssessCommand:
```
    @Override
    public CliInputCommand getCollectCommand() {
        // Collect command
        CliInputCommand collectCmd = new CliInputCommand(CliInputCommand.CMD_COLLECT, "Performs data collection",
                Arrays.asList(targetOption), null, Arrays.asList("arg"));
        return collectCmd;
    }
```

Compile and run without specifying the --target flag.

Inspect the recommendations.json and observe that all targets have been called, as if the command had been called with `--target ""`, rather than the default value specified above.

Optional extra step to verify:
Loop through the options in getCollection or getRecommendation to look for the target option, it will not be found when you run without specifying the `--target` command.

**Expected behavior**
A target option with the default value should be passed through to the getCollection and/or getRecommendation methods as expected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java version: ```
 java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 8.0.7.11 ...
```
 - TA-SDK Version: 0.6.5

**Additional context**
I have a hunch this is possibly related to the changes that went in to fix #98 , if it's specific to the TARGET_OPTION. However I haven't tested if this affects all defaulted options, so that is also a possibility.

**Comment by transformationAdvisor-sdk** [comment]
@ATRG ,  based on the design,  the collect command will not contain option for target.  So during collection phase,  it should collect the config information for all targets,  then in the later phase, like invoke the assess, report or migrate command,  user can generate the specific content for a selected target.  

If in your plug in, in the getCollectCommand() method,  you add the target option,  you need to override the getCollection() method in your plug in,  and use the value for the --target, to perform the business logic for your middleware.

For the assess command,  in the our GenericPluginProvider it provide a default implementation of the getAssessCommand() method, which will add the target option without default value.  In your plug-in class,  do you override the getAssessCommand() method and set your own target option?

**Comment by transformationAdvisor-sdk** [comment]
Find the cause of this problem.  When we compare command options,  we compare long name and shot name either one is the same we think these two option are the same.  In the issue,  there are several options only the long name is different, but without specify the shot name.  Therefore, if in one command more than one of these options are used,  we will just keep the first one and ignore the remaining option with the same short name.
The fix is:  when we try to compare options, will only compare the option long name.

**Comment by transformationAdvisor-sdk** [comment]
done
