### ISSUE TITLE
Document how to get started with the SDK to build a plugin

### ISSUE THREAD

**Issue by johnbuckley** [IBM/transformation-advisor-sdk#20]
**Is your feature request related to a problem? Please describe.**
Describe how to get started and basic concepts

**Describe the solution you'd like**
Getting started guide with associated diagrams

**Describe alternatives you've considered**

**Additional context**

**Comment by transformationAdvisor-sdk** [comment]
The plug-in developer guide wiki page is created.
https://github.com/IBM/transformation-advisor-sdk/wiki/Transformation-Advisor-SDK-Plugin-Developer-Guide
@johnbuckley , Is there any other information you think we need to doc?

**Comment by transformationAdvisor-sdk** [comment]
This issue is completed.
