### ISSUE TITLE
Have the function to set the logging level dynamically

### ISSUE THREAD

**Issue by transformationAdvisor-sdk** [IBM/transformation-advisor-sdk#21]
**Is your feature request related to a problem? Please describe.**
The logging message has leveled,  by default the logging level is debug,  the logging config file in packaged inside the jar file.  This make it not easy to modify the logging level.

**Describe the solution you'd like**
Should have the function to get the logging level from the environment variable,  when this env variable is set,  will use the value of that env variable to set the logging config and use that level in runtime.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by johnbuckley** [comment]
@transformationAdvisor-sdk how about command line arguments like -debug or -verbose.  Do we want output to the console in addition to log file?

**Comment by transformationAdvisor-sdk** [comment]
done
