### ISSUE TITLE
The link to the Slack channel for help in the CONTRIBUTING.md gives a 404

### ISSUE THREAD

**Issue by paulbarr** [IBM/transformation-advisor-sdk#24]
**Describe the bug**
The link to the Slack channel for help in the CONTRIBUTING.md gives a 404

**To Reproduce**
Look at the CONTRIBUTING.md readme
Click on the link for the Slack channel

**Expected behavior**
The Slack channel opens

**Environment (please complete the following information):**
github code

**Comment by transformationAdvisor-sdk** [comment]
The broken link is removed.  Will add it back when the slack channel is ready to use.
