### ISSUE TITLE
Add validation (and generation as appropriate) for all output and input json files 

### ISSUE THREAD

**Issue by paulbarr** [IBM/transformation-advisor-sdk#25]
**Is your feature request related to a problem? Please describe.**
For the plugin developer it is important that the files they define as inputs can be validated against a scheme to smooth development
Output files should be generated where possible to save the developer having to write this code
Additionally all output files and the archive structure they are in should be validated to make sure that created outpost are correct
This will allow for consistency across plugins and smooth upload into TransformationAdvisor

**Describe the solution you'd like**
## Tasks (8 points)

- Validate issues .json
- Validate recommendations.json
- Validate envirnoment.json
- Validate assessmentUnit.json files
- Validate the archive (the zip that bundles up all the output)
- Update the sample plugin code to make sure it's output passes validation
- [ ] Allow all validation to be called individually via a java method

**Describe alternatives you've considered**
Allow the plugin developer to generate all files themselves and be responsible for all validation. This approach makes more work for each plugin developer and has them writing similar code to each other. The proposed enhancement above will avoid this

**Comment by transformationAdvisor-sdk** [comment]
This enhancement is delivered in SDK 0.6.0 release.
