### ISSUE TITLE
Version plugins

### ISSUE THREAD

**Issue by johnbuckley** [IBM/transformation-advisor-sdk#27]
**Is your feature request related to a problem? Please describe.**
Understand whether user should rerun analysis with a new version of collector

**Describe the solution you'd like**
All rules are tagged with the version of the plugin in which they were added

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by transformationAdvisor-sdk** [comment]
@johnbuckley ,  in the packaged jar file,  we already have a version.properties  file created.  This is the content:
```
# cat version.properties 
version=0.5.2
```
 I think we should also support the `--version` option,  so when user use this command,  it should print the SDK version.
```
java -jar ta-sdk-sample-0.5.2.jar --version
```

**Comment by johnbuckley** [comment]
@jianfengk agree. The version command should print both the sdk version (coming from spi jar) and plugin version (coming from plugin jar).  Our sample and doc should show how to change that in the pom.xml and have it flow into plugin jar.  Can default to 0.1.

**Comment by transformationAdvisor-sdk** [comment]
Here is the sample of the version option.
It will display both of the SDK version and plug-in version.
User can overwrite the getVersion() method in their plug-in to set the new version for their plug-in. 

```
# java -jar target/ta-sdk-sample-0.6.0.jar sample version

  Transformation Advisor SDK version: 0.6.0
    - Plugin provider class com.ibm.ta.sdk.sample.SamplePluginProvider version: 0.6.0

```

**Comment by geoghegk** [comment]
why version instead of --version? I guess its been treated as a command, rather than an option, which makes a certain amount of sense - but its out of step with how version would usually work.

**Comment by transformationAdvisor-sdk** [comment]
@geoghegk it will work for both `version` and  `--version`

**Comment by transformationAdvisor-sdk** [comment]
done
