### ISSUE TITLE
Escaped back slashes in collected json lead to empty "occurrences" objects.

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#28]
**Describe the bug**
Back slashes in collected json, such as `"key\\name"` still allow issues under the object to be found, but said issues will return empty occurrence objects like so:
```
                "occurrences": [
                  {},
                  {}
                ]
```

**To Reproduce**
1. Collect json data with a key name including `\\`, in a path to be analysed by a rule.
2. Assess the data with a rule that attempts to find occurrences under that key name
3. Observe empty occurrence objects, and errors in the log like so: 
```
2020-03-02 16:22:00 INFO  IssueRuleProcessor:108 - recommendation path:$['Example']['key\rname']['IOccurManyTimes'][1]
2020-03-02 16:22:00 DEBUG CompiledPath:47 - Evaluating path: $['Example']['key
name']['IOccurManyTimes'][1]['name']
2020-03-02 16:22:00 INFO  IssueRuleProcessor:159 - Attribute not found in JSON, filterPath:$['Example']['key\rname']['IOccurManyTimes'][1] key:name
```

Notice also how the `\r` is evaluated as a carriage return.

The json structure would be:
```
"Example" : { 
"key\\rname" : {
"IOccurManyTimes" [ {"name": "first"}, {"name": "second"} ]
}
}
```

The issue is not seen if the `\\` is removed from the key name.

**Expected behavior**
occurrences section to contain the keys for the found occurrences.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Java version: IBM JDK 8
 - TA-SDK Version 0.5.2

**Additional context**

**Comment by philibm** [comment]
Problem is that the resolved json path, ['Example']['key\rname']['IOccurManyTimes'][1], is not found when reading JSON doc. We need to escape the path, replace '\' with '\\', before reading.

@ATRG @johnbuckley 
What version of SDK is IIB currently on? How would you like this fix delivered (what version of SDK)?
