### ISSUE TITLE
Cannot pull 0.5.2 jars in to maven project.

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#34]
**Describe the bug**
When I copy the dependency information from the README.md in to a maven project, I get the following errors:

```
Downloading from central: https://repo.maven.apache.org/maven2/com/ibm/ta/sdk/ta-sdk/$%7Bta.sdk.version%7D/ta-sdk-$%7Bta.sdk.version%7D.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.714 s
[INFO] Finished at: 2020-03-12T16:24:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ta-plugin-ace: Could not resolve dependencies for project com.ibm.ta.core.plugin:ta-plugin-ace:jar:0.4.0: Failed to collect dependencies at com.ibm.ta.sdk:ta-sdk-core:jar:0.5.2: Failed to read artifact descriptor for com.ibm.ta.sdk:ta-sdk-core:jar:0.5.2: Could not find artifact com.ibm.ta.sdk:ta-sdk:pom:${ta.sdk.version} in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

I think, due to the unusual URL with a $ in it, that it is trying to pull down jar files that do not exit, as the version in the pom files in the maven repository have a string that's trying to read an env var, rather than an actual version number:
`<version>${ta.sdk.version}</version>`
( https://repo.maven.apache.org/maven2/com/ibm/ta/sdk/ta-sdk-core/0.5.2/ta-sdk-core-0.5.2.pom )

**To Reproduce**
1 - Create a maven project with the following dependency:
```
        <dependency>
            <groupId>com.ibm.ta.sdk</groupId>
            <artifactId>ta-sdk-core</artifactId>
            <version>0.5.2</version>
        </dependency>
```
2 - Build the project.

**Expected behavior**
To be able to pull in the project through maven.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Java version: IBM JDK 1.8
 - TA-SDK Version e.g. 0.5.2

**Additional context**
I think you can fix this by just re-uploading the pom.xml files with the correct version number in them.

**Comment by jianfengk** [comment]
Fixed this issue by using the flatten-maven-plugin during deploy time.
A fixpack release 0.5.2-2 was created on maven central repository.
you can use this dependency info in your project.
```
    <dependencies>
        <dependency>
            <groupId>com.ibm.ta.sdk</groupId>
            <artifactId>ta-sdk-core</artifactId>
            <version>0.5.2-2</version>
        </dependency>
    </dependencies>
```

**Comment by ATRG** [comment]
That seems to work, thank you.
Should I close this issue, or do you want me to leave it open?
