### ISSUE TITLE
Issue summary totals in the report always come out as 0 

### ISSUE THREAD

**Issue by geoghegk** [IBM/transformation-advisor-sdk#36]
**Describe the bug**
Issue summary in the report always come out as 0

**To Reproduce**
Run the sample collector and view the html report.

**Expected behavior**
Issue summary shows the number of issues at each severity

**Screenshots**
<img width="963" alt="Screenshot 2020-03-18 at 11 55 55" src="https://user-images.githubusercontent.com/18310573/77309699-04b54f80-6cf5-11ea-86d1-7b8b097015cc.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version na

**Additional context**

**Comment by transformationAdvisor-sdk** [comment]
@geoghegk , Do you find this issue in the sample plug-in or in anther plug-in?
I didnot see this problem in the report generated in the sample plug-in.
<img width="679" alt="Screen Shot 2020-05-25 at 12 23 42 PM" src="https://user-images.githubusercontent.com/52754665/82830155-f6191f00-9e82-11ea-9712-3d4500a7b23e.png">

**Comment by geoghegk** [comment]
@jianfengk It looks like this has been fixed. It was an issue in RecommendationReporter.parseJSON where there was a mismatch between the severity names RED/YELLOW/WARNING and severe/warnign/info.

There is also a typo in the header there I notice:
"Recommendation Reprot..." => "Recommendation Report..."

Thanks.

**Comment by transformationAdvisor-sdk** [comment]
I am use the old code,  the typo was fixed by Paul in this issue #58.
Close this issue.
