### ISSUE TITLE
tarball creation fails to add subfolder contents

### ISSUE THREAD

**Issue by TransformationAdvisor** [IBM/transformation-advisor-sdk#39]
**Describe the bug**
When a tarball is created by the SDK, any subfolders that are a part of the archive are empty.

**To Reproduce**
Run the sample plugin to generate a .tar.gz

**Expected behavior**
The contents of all subfolders should be part of the tarball

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Mac, Windows (possibly all)
 - TA-SDK Version  0.5.2

**Additional context**

**Comment by philibm** [comment]
In 0.5.3, instead of creating a tgz, we are now creating a zip. I've confirmed that the zip archive contains subdirectories.

2 options here:
1. Create a new 0.5.2.x release that will create a zip archive like 0.5.3
2. Or move to use 0.5.3.

**Comment by TransformationAdvisor** [comment]
Thanks Phil. I'll create a  0.5.2.x release. Closing this issue.
