### ISSUE TITLE
Rename field in complexity.json

### ISSUE THREAD

**Issue by geoghegk** [IBM/transformation-advisor-sdk#51]
**Describe the bug**
in complexity.json there is a field called "issuesCategory". It should be called "issueCategories" to align with its intent and with other places (recommendations.json, and coming soon in targets.json)

**To Reproduce**
See `<>transformation-advisor-sdk/ta-sdk-sample/src/main/resources/sample/complexity.json`

**Expected behavior**
N/A.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: All
 - Java version: All
 - TA-SDK Version All

**Additional context**
TA Server will require updates to consume the renamed field.

**Comment by transformationAdvisor-sdk** [comment]
all 4 file issue json file are using plural now.
