### ISSUE TITLE
Reports have a typo in the title - it says 'Reprot' rather then 'Report'

### ISSUE THREAD

**Issue by paulbarr** [IBM/transformation-advisor-sdk#52]
**Describe the bug**
Reports have a typo in the title - it says 'Reprot' rather then 'Report'

**To Reproduce**
Execute the run or report command and lkook at the html file that has been produced

**Expected behavior**
The title should say 'Report'

**Screenshots**
![image](https://user-images.githubusercontent.com/16646094/81810736-66d34980-951b-11ea-82d9-06b055387637.png)

**Environment (please complete the following information):**
All envinroments

**Comment by transformationAdvisor-sdk** [comment]
fixed
