### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by philibm** [IBM/transformation-advisor-sdk#53]
**Is your feature request related to a problem? Please describe.**
The SDK is currently missing a set of unit tests. This will make it easier to add new features in the future.

**Describe the solution you'd like**
A set of unit tests will be added to ta-spi. I will cover validation of the environment.json, recommendations.json, other collected artifacts, creation of the zip, and the JSON validator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by transformationAdvisor-sdk** [comment]
done
