### ISSUE TITLE
Plugin results should be uploadable to IBM Cloud Transformation Advisor server

### ISSUE THREAD

**Issue by johnbuckley** [IBM/transformation-advisor-sdk#57]
**Is your feature request related to a problem? Please describe.**
When running a specific plugin as a new user, I have no idea that the results can be uploaded to TransformationAdvisor server along with results from other plugins

**Describe the solution you'd like**
Include a link to ibm.biz/cloudta
Implement an upload method in the SDK that uses endpoint and auth_key
If endpoint information is not configured (which it will not be by default), print a statement on how to get the endpoint information (KC link) and that result zip can be uploaded manually

**Describe alternatives you've considered**

**Additional context**

**Comment by transformationAdvisor-sdk** [comment]
The main change is done in the TA server side.

**Comment by transformationAdvisor-sdk** [comment]
this is done.  we can upload the sample collection zip file to TA server 2.3.0
