### ISSUE TITLE
zip built on windows has incorrect structure

### ISSUE THREAD

**Issue by paulbarr** [IBM/transformation-advisor-sdk#60]
**Describe the bug**
I got the zip output produced by the CICS team
When I exploded the zip the structure was lost

**To Reproduce**
Set up a plugin env on a windows machine
Build and execute a plugin
The zip produced has lost its internal structure because the file separator is incorrect (I think)

**Expected behavior**
On all OS the structure of the zip should be maintained

**Screenshots**
Try exploding the attached zip file

[CICS_192.168.1.13.zip](https://github.com/IBM/transformation-advisor-sdk/files/4696265/CICS_192.168.1.13.zip)

**Environment (please complete the following information):**
OS: Windows

**Additional context**
When I look in the code for Util.class I see this line
` private static final String ZIP_FILE_SEPARATOR = "/"; // File.separator should not be used in zips`

I see the comment, but something looks wrong here

**Comment by paulbarr** [comment]
Is this fixed now?

**Comment by geoghegk** [comment]
yes, this is fixed. It is a dup of the closed: https://github.com/IBM/transformation-advisor-sdk/issues/40

**Comment by transformationAdvisor-sdk** [comment]
This fix is included in SDK  version 0.5.4.
