### ISSUE TITLE
Ability to omit files containing sensitive data in assessmentUnit archive(s)

### ISSUE THREAD

**Issue by johnbuckley** [IBM/transformation-advisor-sdk#77]
**Is your feature request related to a problem? Please describe.**
Some of the files collected by the collector may contain sensitive data e.g. passwords.  These should not be uploaded to TA without being redacted.

**Describe the solution you'd like**
Plugin should declare the config files being collected, and whether or not those files have been redacted in the assessmentUnit.metadata.json file
The default behaviour should be that final zip archive does not include the collected files unless plugin declares that they do not contain sensitive data.  The reason for having those files in the plugin is (1) for debugging purposes if the recommendations.json does not produce expected results (2) potential future capability to evaluation new rules without having to collect new data.  A "--includeSensitiveFiles" command line option to override this behaviour for the run command.

**Describe alternatives you've considered**
We already have redaction capability in the SDK but sometimes it's not easy to guarantee that you know all the places that need to be redacted.

**Additional context**

**Comment by paulbarr** [comment]
Following on from further discussions with Aaron, this is the plan to tackle this:
 - Add an method to the interface that must be implemented for env.json
    - This method will be containsSensitiveData
    - It should default to true (people have to explicitly override it)
 - When this value is set to true then the .zip file will not be generated
 - When a zip file is not generated it should print out a message explaining why, aka: sensitive data has been included so an uploadable archive has not been generated.

**Comment by philibm** [comment]
@paulbarr @johnbuckley @transformationAdvisor-sdk 
I've created a pull request for master. Please review. I will still need to pull this into v0.5.5 branch and do some sanity testing there as well.

I've also created labels for the releases (v0.5.5 and v0.6.0) and started to add labels to the issues. I can't remember anymore which fixes are in which release and is spending a bit too much time going through pull requests.

**Comment by philibm** [comment]
@jianfeng, for 0.6.0, can you think of a simple pattern for the inclusion of the migration files? If there's a simple pattern, I could implement it. If not, maybe you'll need to take over to finish this part. Thanks.

**Comment by philibm** [comment]
@jianfeng The 0.5.5 branch is ready to go. You may want to do some sanity tests before creating the release and pushing it to maven. The earlier we get it to Aaron's hands and let him do some tests the better.

**Comment by transformationAdvisor-sdk** [comment]
fix was delivered in both 0.5.5 and 0.6.0 release.
