### ISSUE TITLE
Middleware name and assessmentUnit name can clash

### ISSUE THREAD

**Issue by ATRG** [IBM/transformation-advisor-sdk#97]
**Describe the bug**
An assessment unit with the same name as the middleware will clash with the middleware directory

Running, e.g. `TADataCollector middleware run assessmentWithUnitCalledmiddleware` would create
A folder structure as follows:
```
+ output
 | + assessmentWithUnitCalledmiddleware
 |  |  - environment.json
 |  |  - recommendations.json
 |  | + middleware
 |  |  |  - targets.json
 |  |  |  - data.json
 |  |  |  - metadata.assessmentUnit.json
 |  |  |  + templates
 |  |  |  | - targetA
 `--`--`--`-- targetB
 ```

**To Reproduce**
1 - Create an assessment that will create an assessmentUnit with the same name as the middleware, e.g. `middleware` for the ta-sdk-sample.
2 - run the assessment

**Expected behavior**
Running, e.g. `TADataCollector middleware run assessmentWithUnitCalledmiddleware` would create
A folder structure as follows:
```
+ output
 | + assessmentWithUnitCalledmiddleware
 |  |  - environment.json
 |  |  - recommendations.json
 |  | + middleware
 |  |  |  - targets.json
 |  |  |  + templates
 |  |  |  | - targetA
 |  |  `--`-- targetB
 |  |  + middleware  // (I'm not sure how to name the folders to avoid them potentially clashing)
 |  |  |  - data.json
 `--`--`-- metadata.assessmentUnit.json
 ```
 
**Screenshots**
N/A

**Environment (please complete the following information):**
Only been tested on:
 - OS: Windows
 - Java version: IBM JDK 1.8
 - TA-SDK Version: [e.g. 0.5.2]

**Additional context**
N/A

**Comment by transformationAdvisor-sdk** [comment]
fixed
